apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-app
  namespace: gym
  labels:
    app: gym
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        app: gym
        tier: web
    spec:
      volumes:
      - name: vault-token
        emptyDir:
          sizeLimit: 1Mi
      initContainers:
      - name: vault-retrieve
        image: "pi4apps:5000/vault-retrieve:1.2.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_CLOUD_CONFIG_NAME
          value: vault
        - name: SPRING_PROFILES_ACTIVE
          value: dbdev
        - name: SPRING_CLOUD_LABEL
          value: main
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://configs.lavacro.net:9080/"
        - name: SPRING_CLOUD_VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-secrets
              key: token
        volumeMounts:
        - name: vault-token
          mountPath: "/var/tmp/vault"
      containers:
      - name: gym
        image: "pi4apps:5000/gym:2.1.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: profile
          value: pi
        - name: additional_properties
          value: "/var/tmp/vault/vault.properties"
        volumeMounts:
          - name: vault-token
            mountPath: "/var/tmp/vault"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "500m" # 1/2 CPU
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8444
          timeoutSeconds: 60
        #          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8444
          timeoutSeconds: 3
          initialDelaySeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: gym-service
  namespace: gym
spec:
  selector:
    app: gym
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8444
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gym.cloud.lavacro.net
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: gym-service
            port:
              number: 80
