INSERT INTO category VALUES(0, NULL);
INSERT INTO category VALUES(1, 'Upper abs');
INSERT INTO category VALUES(2, 'Obliques');
INSERT INTO category VALUES(3, 'Lower abs');
INSERT INTO category VALUES(4, 'Mid abs');


INSERT INTO exercise VALUES(1, 'Flat bench dumbbell press', 1);
INSERT INTO exercise VALUES(2, 'Pec deck', 1);
INSERT INTO exercise VALUES(3, 'Incline dumbbell press', 1);
INSERT INTO exercise VALUES(4, 'Flat bench flye', 1);
INSERT INTO exercise VALUES(5, 'Incline flye', 1);
INSERT INTO exercise VALUES(6, 'Flat bench barbell press', 1);
INSERT INTO exercise VALUES(9, 'Iso-lateral decline press', 1);
INSERT INTO exercise VALUES(12, 'Seated dumbbell press', 2);
INSERT INTO exercise VALUES(14, 'Front raise', 2);
INSERT INTO exercise VALUES(15, 'Lateral dumbbell raise', 2);
INSERT INTO exercise VALUES(16, 'Bent over lateral dumbbell raise', 2);
INSERT INTO exercise VALUES(17, 'Reverse pec deck', 2);
INSERT INTO exercise VALUES(19, 'Iso-lateral shoulder press', 2);
INSERT INTO exercise VALUES(20, 'One arm dumbbell row', 3);
INSERT INTO exercise VALUES(21, 'Front pull down', 3);
INSERT INTO exercise VALUES(22, 'Reverse grip pull down', 3);
INSERT INTO exercise VALUES(24, 'Seated row', 3);
INSERT INTO exercise VALUES(26, 'Pull-up (wide)', 3);
INSERT INTO exercise VALUES(28, 'Iso-lateral front lat pull-down', 3);
INSERT INTO exercise VALUES(29, 'Dumbbell shrug', 4);
INSERT INTO exercise VALUES(30, 'Upright row', 4);
INSERT INTO exercise VALUES(31, 'Barbell shrug', 4);
INSERT INTO exercise VALUES(32, 'Upright cable row', 4);
INSERT INTO exercise VALUES(33, 'Back extension', 5);
INSERT INTO exercise VALUES(34, 'Back extension (sides)', 5);
INSERT INTO exercise VALUES(35, 'Deadlift', 5);
INSERT INTO exercise VALUES(36, 'Standing barbell/EZ-Bar curl', 6);
INSERT INTO exercise VALUES(37, 'Standing dumbbell curl', 6);
INSERT INTO exercise VALUES(38, 'Dumbbell incline curl', 6);
INSERT INTO exercise VALUES(39, 'Preacher curl', 6);
INSERT INTO exercise VALUES(40, 'Machine preacher curl', 6);
INSERT INTO exercise VALUES(41, 'Concentration curl', 6);
INSERT INTO exercise VALUES(42, 'Hammer curl', 6);
INSERT INTO exercise VALUES(45, 'Dumbbell overhead extension', 7);
INSERT INTO exercise VALUES(46, 'Seated overhead EZ-bar extension', 7);
INSERT INTO exercise VALUES(48, 'Pressdown', 7);
INSERT INTO exercise VALUES(49, 'Dumbbell kickback', 7);
INSERT INTO exercise VALUES(50, 'Close-grip bench press', 7);
INSERT INTO exercise VALUES(52, 'Crunch', 8);
INSERT INTO exercise VALUES(53, 'Decline bench crunch', 8);
INSERT INTO exercise VALUES(56, 'Oblique crunch', 8);
INSERT INTO exercise VALUES(58, 'Hanging knee raise', 8);
INSERT INTO exercise VALUES(60, 'Romanian deadlift', 9);
INSERT INTO exercise VALUES(61, 'Lying leg curl', 9);
INSERT INTO exercise VALUES(62, 'Standing leg curl', 9);
INSERT INTO exercise VALUES(63, 'Standing calf raise', 10);
INSERT INTO exercise VALUES(64, 'Seated calf raise', 10);
INSERT INTO exercise VALUES(65, 'Donkey calf raise', 10);
INSERT INTO exercise VALUES(67, 'Front squat', 11);
INSERT INTO exercise VALUES(68, 'Leg extension', 11);
INSERT INTO exercise VALUES(70, 'Leg sled', 11);
INSERT INTO exercise VALUES(71, 'Seated leg press', 11);
INSERT INTO exercise VALUES(72, 'Leg press', 11);
INSERT INTO exercise VALUES(74, 'Wrist curl', 12);
INSERT INTO exercise VALUES(75, 'Reverse wrist curl', 12);
INSERT INTO exercise VALUES(18, 'Lateral raise machine', 2);
INSERT INTO exercise VALUES(13, 'Shoulder press', 2);
INSERT INTO exercise VALUES(44, 'Lying french press', 7);
INSERT INTO exercise VALUES(76, 'Two-hand dumbbell overhead ext.', 7);
INSERT INTO exercise VALUES(79, 'Lower back extension', 5);
INSERT INTO exercise VALUES(11, 'Flye (machine)', 1);
INSERT INTO exercise VALUES(80, 'Chest Press', 1);
INSERT INTO exercise VALUES(81, 'Calf Extension', 10);
INSERT INTO exercise VALUES(7, 'Seated leg curl', 9);
INSERT INTO exercise VALUES(54, 'Abdominal machine', 8);
INSERT INTO exercise VALUES(10, 'Incline press', 1);
INSERT INTO exercise VALUES(23, 'MTS Shoulder Press', 2);
INSERT INTO exercise VALUES(8, 'Smith-Machine Flat Press', 1);
INSERT INTO exercise VALUES(25, 'Smith-Machine Incline Press', 1);
INSERT INTO exercise VALUES(43, 'Triceps Extension', 7);
INSERT INTO exercise VALUES(47, 'MTS Abdominal Crunch', 8);
INSERT INTO exercise VALUES(51, 'Biceps curl machine', 6);
INSERT INTO exercise VALUES(55, 'Row/rear deltoid', 3);
INSERT INTO exercise VALUES(57, 'Abdominal Crunch Machine (horiz)', 8);
INSERT INTO exercise VALUES(59, 'Torso rotation', 8);
INSERT INTO exercise VALUES(69, 'Triceps press', 7);
INSERT INTO exercise VALUES(73, 'Abductors', 11);
INSERT INTO exercise VALUES(77, 'Adductors', 11);
INSERT INTO exercise VALUES(78, 'Cross-body hammer curls', 6);
INSERT INTO exercise VALUES(82, 'One-arm dumbbell preacher curls', 6);
INSERT INTO exercise VALUES(83, 'Preacher hammer dumbell curls', 6);
INSERT INTO exercise VALUES(84, 'Reverse grip triceps pushdown', 7);
INSERT INTO exercise VALUES(85, 'Assisted pull-ups', 3);
INSERT INTO exercise VALUES(86, 'Assisted dips', 7);
INSERT INTO exercise VALUES(87, 'Glutes machine', 11);
INSERT INTO exercise VALUES(88, 'Fixed pulldown', 3);
INSERT INTO exercise VALUES(89, 'Iso-lateral row', 3);
INSERT INTO exercise VALUES(90, 'Reverse-grip pull-ups', 6);
INSERT INTO exercise VALUES(91, 'Ab Coaster (sides)', 8);
INSERT INTO exercise VALUES(92, 'Ab Coaster', 8);
INSERT INTO exercise VALUES(93, 'Ab Carver', 8);
INSERT INTO exercise VALUES(94, 'Dual pulley pulldown', 3);
INSERT INTO exercise VALUES(95, 'Sit-ups', 8);
INSERT INTO exercise VALUES(96, 'Decline press', 1);
INSERT INTO exercise VALUES(97, 'Back squat', 11);
INSERT INTO exercise VALUES(66, 'Smith Machine back squat', 11);
INSERT INTO exercise VALUES(98, 'Tricep incline extension', 7);
INSERT INTO exercise VALUES(99, 'Spider curl', 6);
INSERT INTO exercise VALUES(100, 'Hex bar', 4);
INSERT INTO exercise VALUES(102, 'Dual pulley row', 3);
INSERT INTO exercise VALUES(101, 'Cable one arm tricep extension', 7);
INSERT INTO exercise VALUES(103, 'Cable cross-over', 1);
INSERT INTO exercise VALUES(104, 'FreeMotion crossover', 1);
INSERT INTO exercise VALUES(105, 'MTS Row', 3);
INSERT INTO exercise VALUES(27, 'Iso-lateral low row', 3);
INSERT INTO exercise VALUES(106, 'Pull-ups', 6);
INSERT INTO exercise VALUES(107, 'Straight-arm pressdown', 3);
INSERT INTO exercise VALUES(108, 'Lying Tricep Extension', 7);
INSERT INTO exercise VALUES(109, 'Face pull', 3);
INSERT INTO exercise VALUES(110, 'Iso-lateral press', 1);
INSERT INTO exercise VALUES(111, 'Pully crunch', 8);
INSERT INTO exercise VALUES(112, 'Pulldown', 3);
INSERT INTO exercise VALUES(113, 'Leg Extension (single)', 11);
INSERT INTO exercise VALUES(114, 'Seated Leg Curl (single)', 9);

INSERT INTO muscle VALUES(1, 'Chest');
INSERT INTO muscle VALUES(2, 'Shoulders');
INSERT INTO muscle VALUES(3, 'Upper Back');
INSERT INTO muscle VALUES(4, 'Traps');
INSERT INTO muscle VALUES(5, 'Lower Back');
INSERT INTO muscle VALUES(6, 'Biceps');
INSERT INTO muscle VALUES(7, 'Triceps');
INSERT INTO muscle VALUES(8, 'Abdominals');
INSERT INTO muscle VALUES(9, 'Hamstrings');
INSERT INTO muscle VALUES(10, 'Calves');
INSERT INTO muscle VALUES(11, 'Thights/Glutes');
INSERT INTO muscle VALUES(12, 'Forearms');

INSERT INTO allprogress (progid, exerciseid, exercise, muscle, mydate, weight, rep1) VALUES(1, 1, 'cross-body hammer curl', 'biceps', '202311', 45.0, 4);
INSERT INTO allprogress (progid, exerciseid, exercise, muscle, mydate, rep1, rep2) VALUES(2, 2, 'hanging knee raise', 'abdominals', '202311', 18, 15);
INSERT INTO allprogress (progid, exerciseid, exercise, muscle, mydate, weight, rep1) VALUES(3, 4, 'smith machine bench press', 'chest', '202310', 140.0, 5);
